[package]
name = "citool"
version = "0.1.0"
edition = "2021"

[dependencies]
# Basic dependencies needed for calculating the CI job matrix
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
glob-match = "0.2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"

csv = { version = "1", optional = true }
diff = { version = "0.1", optional = true }
ureq = { version = "3", features = ["json"], optional = true }

build_helper = { path = "../../build_helper", optional = true }

[features]
default = ["extended"]
# Features needed for more advanced analysis and network requests
extended = ["dep:csv", "dep:diff", "dep:ureq", "dep:build_helper"]

[dev-dependencies]
insta = "1"

# Tell cargo that citool is its own workspace.
# If this is omitted, cargo will look for a workspace elsewhere.
# We want to avoid this, since citool is independent of the other crates.
[workspace]

# Make compilation faster
[profile.dev]
debug = 0
